### ISSUE TITLE
Problem with rules update - getting error "Rules are stale: Rules are older then two weeks"

### ISSUE THREAD

**Issue by chrudosvorlicek** [lightswitch05/php-version-audit#186]
Hi,

since today I'm getting error `Rules are stale: Rules are older then two weeks`. Since it is not common error when dealing with php version audit, I start digging deeper. First of all, I tried call composer update but version was the newest available, which is `1.20240802.0`.

This forced me to look closer to the package itself and I found out that there is a problem with github actions, specifically it's call of [docker-compose](https://github.com/lightswitch05/php-version-audit/actions/runs/10413469055/job/28840915389#step:8:8).

Can you look at it?

**Comment by lightswitch05** [comment]
Thanks for letting me know. I don't use this anymore personally, so was not aware that updates have broken. I'll try to get it fixed in the next couple days

**Comment by lightswitch05** [comment]
@chrudosvorlicek should be fixed now, thanks for the bug report!===

**Comment by chrudosvorlicek** [comment]
@lightswitch05 thanks for fast fix
